import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

import Launch from './Launch.jsx';
import Welcome from './Welcome.jsx';
import Navigator from './Navigator.jsx';

// In React Native, we have three main files, Launch.jsx, Welcome.jsx, and Navigator.jsx, that the rest of the app will be built on
// Therefore, do not edit this file
export default function App() {

  const Stack = createNativeStackNavigator();
  return (
    <>
      <NavigationContainer>
        <Stack.Navigator
          screenOptions={
            {
              headerShown: false,
              animation: 'none',
            }
          }
        >

          <Stack.Screen name="Launch" component={Launch} options={{title: 'Launch Screen'}} />
          <Stack.Screen name="Welcome" component={Welcome} options={{title: 'Welcome Screen'}} />
          <Stack.Screen name="Navigator" component={Navigator} options={{title: 'Navigator Screen'}} />

        </Stack.Navigator>
      </NavigationContainer>
  </>
);
}
